[package]
name = "safebox"
version = "0.1.0"
authors = ["Fran√ßois-Xavier Bourlet <bombela@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rand = "0.7"
